:C: BATCH ACCOUNTING

                BATCH ACCOUNTING PROGRAM
                ------------------------

INTRODUCTION
------------

        THE BCHARGE PROGRAM IS USED TO ENTER BATCH REQUEST (ALSO
CALLED PPR'S - PERIPHERAL PROCESSING REQUESTS) INTO THE ACCOUNTING
SYSTEM.  THE PROGRAM USES INFORMATION IN THE FILE (*1BATCH)
PARCHG.DAT WHICH IS UPDATED WHEN A CUSTOMER ENTERS A BATCH OR SPOOL
REQUEST.
        
VALID COMMANDS
--------------
        
        COMMANDS MAY BE SHORTENED TO THE FIRST THREE CHARACTERS

        LIST #          -         FOR REQUEST BEARING #
                                  IF UNPROCESSED, TYPES REQ. NO., GAN,
                                  CUST. NO., DIST. NO., USER NAME, 
                                  PROJ. CODE, AND NAME OF THE REQUESTOR,
                                  AND THE DATE THE REQUEST WAS CREATED.
                                  IF IT IS A VOIDED REQUEST THE NAME OF
                                  THE OPERATOR VOIDING THE REQUEST WILL
                                  BE ADDED.  INFORMATION ON PROCESSED
                                  REQUESTS ALSO INCLUDE BATCH TYPE,
                                  VOLUME, DECOLLATION CHARGE IF ANY,  
                                  POSTAGE IF ANY, AND TOTAL CHARGE.
                                  HOWEVER, THE CREATION DATE IS NOT
                                  AVAILABLE FOR PROCESSED REQUESTS.

        LIST PROCESSED  -         OUTPUTS THE ABOVE INFORMATION TO THE
                                  TELETYPE OR TO A FILE FOR ALL
                                  PROCESSED REQUESTS.

        LIST UNPROCESSED-         *OUTPUTS THE ABOVE INFORMATION TO THE
                                  TELETYPE OR TO A FILE FOR ALL UN-
                                  PROCESSED REQUESTS.

        LIST VOID       -         OUTPUTS THE ABOVE INFORMATION TO THE
                                  TELETYPE OR TO A FILE FOR ALL VOIDED
                                  REQUESTS.

        CHARGE #        -         INPUTS CHARGES FOR REQUEST BEARING #.

        CHARGE ALL      -         PRESENTS ALL UNPROCESSED REQUESTS TO
                                  THE USER FOR INPUT OF CHARGES.

        HOLD #          -         ENABLES A BCHARGE REQUEST TO BE
                                  RETAINED WHILE POSTAGE OR 
                                  TRANSPORTATION CHARGES ARE OBTAINED.
                                  THIS PRESERVES THE REQUEST EVEN THOUGH
                                  THE MONTH END ACCOUNTING HAS BEEN RUN.

        HOLD #          -         RETAINS AN UNPROCESSED BATCH ACCOUNTING
        RECHARGE #      -         ALLOWS RE-ENTERING ALL DATA FOR A
                                  REQUEST, THEN INVALIDATES THE OLD
                                  RECORDS  
        
        POSTAGE #       -         ALLOWS ADDING OR CORRECTING POSTAGE
                                  CHARGES. 

        CREATE          -         ALLOWS FOR CREATING A BATCH BCHARGE
                                  FROM INFORMATION SUPPLIED BY THE USER
                                  PROGRAM.

        VOID #          -         VOIDS THE UNPROCESSED REQUEST
                                  BEARING #.

        QUIT OR Q       -         QUITS TO THE EXEC

        HELP OR ?       -         REPRINTS THIS LIST

*IF THIS COMMAND INCLUDES A DATE ONLY UNPROCESSED REQUESTS 
 CREATED ON OR BEFORE THIS DATE WILL BE LISTED

OPERATING INSTRUCTIONS
----------------------

                        ACCOUNTING FOR BATCH REQUESTS
                        -----------------------------

        ALL BATCH REQUESTS, EXCEPT SPOOL (WHICH ARE HANDLED DIF-
FERENTLY), ARE ENTERED INTO ACCOUNTING WHETHER OR NOT POSTAGE OR
TRANSPORTATION CHARGES ARE DUE.  HOWEVER, ON THE LAST DAY OF THE
MONTH BATCH ACCOUNTING MAY BE DEFERRED IF YOU ARE NOT ABLE TO OBTAIN
POSTAGE CHARGES.

        THERE ARE SEVEN JOB TYPES THAT OPERATORS CAN PERFORM VIA A PPR.

        TYPE 1: LISTINGS; SPOOL SHOULD BE USED FOR LISTINGS INSTEAD
OF BATCH REQUESTS; IF A BATCH REQUEST IS USED THE FOLLOWING ITEMS ON
THE REQUEST PERTAIN:

       *1-----PAGES-----PARTS TO LISTING-----LISTING DECOLLATED

       JOB TYPE 2 AND 3: CARD WORK; READING WITH PIP; PUNCHING
ON 940'S.
       *2-----CARDS TO DISC    *3-----DISC TO CARDS

       TYPE 4: RESTORES; TITO, FAILSA, 1STORE, MAGCON, VARREC,
OR VARIAN.
       *4-----FILES TAPE TO DISC

       TYPE 5: STORES; TITO, 1STORE, MAGCON, VARIAN AND VARREC;
USER MAY NEED TO BUY A TAPE FOR $40.00.
       *5-----FILES TO DISC TO TAPE-----TAPE CHARGE

       TYPE 6: MAGNETIC TAPE CONVERSIONS; MAGCON, VARREC AND
VARIAN; CHARGE IS $30.00 PER JOB.
       6-----OTHER CHARGE      *7-----TAPE CONVERSION

        TYPE 7: EUROPEAN STORES OR RESTORES; THESE CAUSE A CURRENCY
CONVERSION AND OTHER ACCOUNTING DIFFERENCES WITH BCHARGE.
       *8-----EUROPEAN BATCH

(*= JOB TYPES)


        AFTER A BATCH REQUEST HAS BEEN COMPLETED THE OPERATOR
SIGNS AND DATES THE REQUEST. NEXT THE BCHARGE PROGRAM SHOULD BE
RUN. THIS PROGRAM ACCEPTS INPUTS CONCERNING THE  WORK THAT WAS JUST
COMPLETED AND IS INDEXED BY THE PPR (PERIPHERAL PROCESSING REQUEST)
NUMBER. THE FILE (*1BATCH)PARCHG.DAT IS SEARCHED FOR THE REQUEST 
NUMBER AND, ONCE THE BCHARGE RUN HAS BEEN COMPLETED, THE FINISHED
ACCOUNTING INFORMATION IS OUTPUT TO (*1BATCH)BATONN.MON WHERE
NN IS THE SYSTEM NUMBER AND MON IS THE ABBREVIATED MONTH.


        IF THE REQUEST HAS NOT BEEN ENTERED INTO ACCOUNTING, IT
SHOULD BE 'QA'D' BY THE LEAD OPERATOR/BATCH CONTROLLER AND THEN
FILED IN THE SYSTEM FOLDER FOR 'BCHARGE DUE' REQUESTS.  IF IT
HAS BEEN ENTERED INTO ACCOUNTING IT CAN BE FILED IN THE SYSTEM
FOLDER FOR COMPLETED REQUESTS.

        IF POSTAGE OR TRANSPORTATION CHARGES ARE DUE, TWO COPIES
OF THE REQUEST ARE MADE AND CLIPPED TO THE JOB.  THE ORIGINAL
REQUEST AND THE JOB HARDCOPY ARE FILED.  WHEN THE JOB IS MAILED,
A COPY OF THE REQUEST SHOULD BE SENT WITH THE JOB AND THE OTHER
COPY IS MARKED WITH THE CHARGES AND PLACED IN THE APPROPRIATE
FOLDER.

        WHEN THE LEAD OPERATOR/BATCH CONTROLLER, PICKS UP
THESE COPIES, THEY ARE DISTRIBUTED TO THE OPERATOR OF THE
PARTICULAR SYSTEM INVOLVED, SO THAT POSTAGE CAN BE ENTERED USING
THE 'POSTAGE' COMMAND.  THE MINIMUM CHARGE ALLOWED IS $00.13.
AFTER BCHARGE IS RUN, THE TTY OUTPUTS SHOULD BE ATTACHED TO THE
REQUEST AND RETURNED TO BATCH CONTROL.

        IT IS THE RESPONSIBILITY OF LEAD OPERATORS OR BATCH
CONTROLLERS, TO ENSURE THAT ALL BATCH REQUESTS ARE PROPERLY
ENTERED INTO ACCOUNTING.


                        ACCOUNTING FOR SPOOL REQUESTS
                        -----------------------------

        THE SPOOL PROGRAM PRINTS OUT A HARDCOPY TO THE SUPCHECK TTY,
ALLOWING THE LEAD OPERATOR/BATCH CONTROLLER TO QUEUE REQUESTS BY
PAPER TYPE.  IN THIS WAY, IT SHOULD BE POSSIBLE TO MINIMIZE SET-UP
TIME BY PRINTING ALL REQUESTS OF A CERTAIN PAPER TYPE AT ONE SESSION
USING THE 'TAPE' COMMAND FOR FILES FROM ANOTHER SYSTEM.  THE
LEAD OPERATOR/BATCH CONTROLLER SHOULD PAY CLOSE ATTENTION TO ALL 
RELEVENT SPOOL INFORMATION BEFORE PRINTING IS STARTED FOR CASES
WHERE SPECIAL DELIVERY INSTRUCTIONS SHOULD BE USED FOR ASSIGNING
PRIORITY (I. E. AIR MAIL, SPECIAL DELIVERY JOBS MIGHT BE DONE
IMMEDIATELY RATHER THAN HELD FOR OTHER SPOOL REQUESTS OF THE SAME
PAPER TYPE).

        THE SPOOL REQUESTS SHOULD BE ANALYZED, LOGGED IN AND THEN
GIVEN TO THE SYSTEM OPERATOR TO BE PRINTED.  AFTER THE PRINTING IS
COMPLETED, A COPY OF THE REQUEST WILL BE PRINTED OUT TO THE OPERATOR'S
TTY.  AT THE END OF THE REQUEST THERE WILL BE A STATEMENT INDICATING
WHETHER OR NOT THE REQUEST SHOULD BE ENTERED INTO ACCOUNTING.

        THE FOLLOWING PARAGRAPHS DESCRIBE WHAT THE SPOOL PROGRAM
DOES AND WHAT STEPS THE OPERATOR TAKES TO ENTER IT INTO ACCOUNTING.

        THE SPOOL PROGRAM WILL PLACE RECORDS IN THE UNPROCESSED BATCH
RECORD FILES UNDER THE FOLLOWING CONDITIONS:

        A.  WHEN THE MODE OF DELIVERY IS OTHER THAN PICKUP.

        B.  WHEN THE SPOOL PROGRAM WAS UNABLE TO ACCESS THE
            PROCESSED BATCH RECORD FILE WITH A COMPLETED
            RECORD.

        C.  WHEN THE SPOOL PROGRAM WAS UNABLE TO ACCESS THE
            BATCH CHARGE RATE FILE.

        WHENEVER THE 'CHARGE' COMMAND IS CALLED, BCHARGE WILL SCAN
THE UNPROCESSED BATCH RECORD FILE FOR ANY SPOOLING RECORDS FALLING
UNDER CATEGORY B AND WILL MOVE THEM TO THE PROCESSED BATCH RECORD
FILE.

        RECORDS FALLING UNDER CATEGORY A AND C WILL REMAIN IN THE
UNPROCESSED BATCH RECORD FILE IDENTIFIED BY THE COMMENT
"SPOOL RECORD AWAITING POSTAGE CHARGES" UNTIL THE OPERATOR
RUNS THE CHARGE COMMAND AGAINST THAT RECORD.  THE OPERATOR
WILL ONLY BE PRESENTED WITH THE QUESTION "ENTER POSTAGE OR
TRANSPORTATION CHARGES" WHEN CHARGING A SPOOLING RECORD.

        UPON CAREFUL COMPLETION OF A SPOOL JOB, THE SPOOL REQUEST
HARDCOPY IS INITIALED BY THE OPERATOR AND RETURNED TO BATCH CONTROL
AREA WITH THE JOB.

        AFTER IT IS CHECKED FOR ACCURACY, QUALITY OF PRINT, AND
COMPLETENESS, IT WILL BE PLACED IN THE MAIL ROOM ON THE SHELF
DESIGNATED FOR MAILING.

        EXCEPTIONS TO THIS ARE THOSE JOBS THAT NEED IMMEDIATE ATTEN-
TION.  THE LEAD OPERATOR/BATCH CONTROLLER SHOULD PERFORM THE TASK OF
GETTING THE REQUEST READY FOR PICKUP AND DELIVERY, COMPLETING THE
NECESSARY PAPERWORK, AND CALLING THE DELIVERY COMPANY.  THE HARDCOPY
SHOULD THEN BE FILED.

        WHEN THE MAILING OF SPOOL REQUESTS HAS BEEN COMPLETED,
A COPY SHOULD BE PLACED IN THE FOLDER DESIGNATED FOR PICKUP.  THE
OPERATOR SHOULD RUN BCHARGE USING THE COMMAND 'CHARGE' TO ENTER IT
INTO ACCOUNTING, OR THE COMMAND 'POSTAGE' IF THE REQUEST HAS BEEN
ENTERED AND IS AWAITING 'DELIVERY' CHARGES.  THE TTY OUTPUT SHOULD
BE ATTACHED TO THE REQUEST AND RETURNED TO BATCH CONTROL.


SAMPLE OUTPUT
-------------

       ENTERING A BATCH REQUEST
       ------------------------

               A.  IN THE EXEC TYPE:

               -1BCHARGE

               BATCH ENTRY PROGRAM VERSION (CURRENT VERSION)

               >CHARGE #                (WHERE # IS THE REQUEST NO.
                                         TO BE ENTERED INTO
                                         ACCOUNTING)

               YOUR NAME:

               YOUR PASSWORD:

               REQUEST NO:              (REQUEST NO. CAN BE ENTERED
                                         HERE IF NOT ENTERED ABOVE)

                REG.    GAN  CUST DIST USER NAME   PROJ CODE   REQ. BY
               05694   6017  4109   20 PARTS       WPROCESS    PARTS
               REQ. DATE 05-13-75

               OKAY?

       (ENTER 'Y' IF THE ITEMS OUTPUT ABOVE MATCH THE ACTUAL REQUEST.
        ENTER 'N' IF THINGS DON'T MATCH AND CHECK TO SEE IF REQUEST #
        ENTERED WAS CORRECT AND IF SO, BRING ALL OUTPUT TO LEAD
        OPERATOR/BATCH CONTROLLER)

               COMPLETION DATE: (MM-DD-YY)

       (ENTER DATE REQUEST WAS COMPLETED)

               BATCH TYPE:

       (ENTER NUMBER INDICATED ON BATCH REQUEST.  THESE NUMBERS
        RANGE FROM 1 TO 8.  IF NUMBER 1 IS ENTERED, PROGRAM
        PROMPTS WITH)

               PAGES:

               PARTS:

       (ENTER TOTAL PAGES PRINTED AND PARTS.  WHEN ENTERING A 2,
        3, OR 4, THE PROGRAM PROMPTS WITH)

               WERE LISTINGS DECOLLATED?

       (A 'Y' WILL BE ENTERED HERE.  BATCH TYPE 1 MAY NEED TO BE
        USED A COUPLE OF TIMES, DEPENDING ON THE NUMBER OF PARTS
        NEEDED BY THE REQUESTOR.  AFTER PROVIDING ALL INFORMATION
        FOR BATCH TYPE 1, THE PROGRAM WILL ASK)

               ANOTHER BATCH TYPE FOR THIS REQUEST?

       (IF 'Y' IS ENTERED THE PROGRAM WILL ASK FOR THE NEXT BATCH
        TYPE.  IF THERE IS, ENTER IT AT THIS TIME.  IF 'N' IS
        ENTERED, PROGRAM  WILL ASK)

               ANY POSTAGE OR OTHER TRANSPORTATION CHARGE?

       (A 'N' WILL BE ENTERED HERE.  THE NEXT PROMPT WILL BE)

               ALL ENTRIES CORRECT?

       (IF 'N' IS GIVEN IN RESPONSE TO THIS QUESTION, YOU WILL 
        NEED TO REENTER ALL DATA AGAIN.  IF 'Y' IS ENTERED THE
        PROGRAM WILL ASK)

               ANOTHER REQUEST?

       (IF 'Y' IS GIVEN IN RESPONSE TO THIS PROMPT, THE PROGRAM
        WILL PROMPT WITH 'REQUEST NO.'.  IF 'N' IS GIVEN TO THIS
        PROMPT, YOUR NEXT PROMPT WILL BE)

               >

       (ENTERING A 'Q' HERE RETURNS YOU TO THE EXEC)



       ENTERING A SPOOL REQUEST
       ------------------------

               USING THE 'CHARGE' COMMAND
               --------------------------

               A.  IN THE EXEC TYPE:

               -1BCHARGE

               BATCH ENTRY PROGRAM VERSION (CURRENT VERSION)

               >CHARGE #               (THE SPOOL REQUEST #
                                        TO BE ENTERED)

               YOUR NAME:

               YOUR PASSWORD:
       (HERE ALL INFORMATION PERTAINING TO THE REQUEST IS PRINTED,
        I.E., REG NO., GAN, CUST, DIST, USER NAME, PROJ CODE, AND
        WHO REQUESTED THE JOB BE PERFORMED ALONG WITH THE REQUESTED
        DATE)
               
               SPOOL RECORD AWAITING POSTAGE CHARGES

               OKAY?                   (DO DETAILS MATCH THE REQUEST?
                                        SEE COMMENTS IN SAMPLE BATCH
                                        OUTPUT ABOVE)

               ENTER POSTAGE OR TRANSPORTATION CHARGE: 5.00

        (DELIVERY CHARGES ARE ENTERED HERE)

               ALL ENTRIES CORRECT?    (SEE COMMENTS IN SAMPLE BATCH
                                        OUTPUT ABOVE)

                ANOTHER REQUEST?        (SEE COMMENTS IN SAMPLE BATCH
                                        OUTPUT ABOVE)

               >                       (RETURNS TO EXEC)

               -



               USING THE 'POSTAGE' COMMAND
               ---------------------------

               A.  IN THE EXEC TYPE:

               -1BCHARGE

               BATCH ENTRY PROGRAM VERSION (CURRENT VERSION)

               >POSTAGE #               (SEE COMMENTS IN SAMPLE
                                         OUTPUT ABOVE)

               YOUR NAME:

               YOUR PASSWORD:
       (HERE ALL INFORMATION PERTAINING TO THE REQUEST IS OUTPUTED)

               OKAY?                    (SEE COMMENTS IN SAMPLE
                                         OUTPUT ABOVE)

               ENTER NEW TRANSPORTATION CHARGES: 1.97

        (DELIVERY CHARGES ARE ENTERED HERE)

               ALL ENTRIES CORRECT?     (SEE COMMENTS IN SAMPLE
                                         OUTPUT ABOVE)

               >                        (RETURN TO EXEC)

               -



ERROR MESSAGES
--------------

        ANY ERRORS ENCOUNTERED WHILE RUNNING THE BATCH ACCOUNT-
        ING PROGRAM SHOULD BE BROUGHT TO THE ATTENTION OF THE LEAD
        OPERATOR/BATCH CONTROLLER.

 